-- Thêm nhân viên
ALTER PROCEDURE spInsertNhanVien
@MANV VARCHAR(15),
@HOTEN NVARCHAR(30),
@GIOITINH NVARCHAR(5),
@NGAYSINH DATE,
@DIACHI NVARCHAR(30),
@DIENTHOAI VARCHAR(10),
@NGAYVAOLAM DATE,
@GHICHU NVARCHAR(35)
AS
BEGIN
INSERT INTO	dbo.NHANVIEN
(
    MANV,
    HOTEN,
    GIOITINH,
    NGAYSINH,
    DIACHI,
    DIENTHOAI,
    NGAYVAOLAM,
    GHICHU
)
VALUES
(   @MANV,        -- MANV - varchar(15)
    @HOTEN,       -- HOTEN - nvarchar(30)
    @GIOITINH,       -- GIOITINH - nvarchar(5)
    @NGAYSINH, -- NGAYSINH - date
    @DIACHI,       -- DIACHI - nvarchar(30)
    @DIENTHOAI,        -- DIENTHOAI - varchar(10)
    @NGAYVAOLAM, -- NGAYVAOLAM - date
    @GHICHU        -- GHICHU - nvarchar(35)
    )
END
GO
-- Update nhân viên
ALTER PROCEDURE spUpdateNhanVien
@MANV VARCHAR(15),
@HOTEN NVARCHAR(30),
@GIOITINH NVARCHAR(5),
@NGAYSINH DATE,
@DIACHI NVARCHAR(30),
@DIENTHOAI VARCHAR(10),
@NGAYVAOLAM DATE,
@GHICHU NVARCHAR(35)
AS
BEGIN
UPDATE dbo.NHANVIEN SET 
HOTEN = @HOTEN,
GIOITINH = @GIOITINH,
NGAYSINH = @NGAYSINH,
DIACHI = @DIACHI,
DIENTHOAI = @DIENTHOAI,
NGAYVAOLAM = @NGAYVAOLAM,
GHICHU = @GHICHU 
WHERE MANV = @MANV
END
--Xóa nhân viên
GO
ALTER PROCEDURE spDeleteNhanVien
@MANV VARCHAR(15)
AS
BEGIN
DELETE FROM dbo.NHANVIEN WHERE MANV = @MANV
END
