-- Insert CustomerType
ALTER PROCEDURE spInsertLoaiKhachHang
@MALOAIKH VARCHAR(15),
@TENLOAI NVARCHAR(30)
AS
BEGIN
	INSERT INTO	dbo.LOAIKHACHHANG
	(
	    MALOAIKH,
	    TENLOAI
	)
	VALUES
	(   @MALOAIKH, -- MALOAIKH - varchar(15)
	    @TENLOAI -- TENLOAI - nvarchar(30)
	    )
END
GO
-- Update CustomerType
ALTER PROCEDURE spUpdateLoaiKhachHang
@MALOAIKH VARCHAR(15),
@TENLOAI NVARCHAR(30)
AS
BEGIN
	UPDATE dbo.LOAIKHACHHANG 
	SET TENLOAI = @TENLOAI
	WHERE MALOAIKH = @MALOAIKH
END
GO
-- Delete CustomerType
ALTER PROCEDURE spDeleteLoaiKhachHang
@MALOAIKH VARCHAR(15)
AS
BEGIN
	DELETE FROM dbo.LOAIKHACHHANG WHERE MALOAIKH = @MALOAIKH 
END
GO