-- Insert nhóm sản phẩm
ALTER PROCEDURE spInsertNhomSanPham
@MANHOMSP VARCHAR(15),
@TENNHOMSP NVARCHAR(30)
AS
BEGIN
INSERT INTO dbo.NHOMSANPHAM
(
    MANHOMSP,
    TENNHOMSP
)
VALUES
(   @MANHOMSP, -- MANHOMSP - varchar(15)
    @TENNHOMSP -- TENNHOMSP - nvarchar(30)
    )
END
GO
-- Update nhóm sản phẩm
ALTER PROCEDURE spUpdateNhomSanPham
@MANHOMSP VARCHAR(15),
@TENNHOMSP NVARCHAR(30)
AS
BEGIN
UPDATE dbo.NHOMSANPHAM
SET TENNHOMSP = @TENNHOMSP
WHERE MANHOMSP = @MANHOMSP
END
GO
-- DELETE nhóm sản phẩm
ALTER PROCEDURE spDeleteNhomSanPham
@MANHOMSP VARCHAR(15)
AS
BEGIN
DELETE dbo.NHOMSANPHAM WHERE MANHOMSP = @MANHOMSP
END
GO
